// <auto-generated />
namespace StudentApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class added_department : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_department));
        
        string IMigrationMetadata.Id
        {
            get { return "202002280048419_added_department"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
