// <auto-generated />
namespace StudentApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class removed_age_constraint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removed_age_constraint));
        
        string IMigrationMetadata.Id
        {
            get { return "202002272020131_removed_age_constraint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
