// <auto-generated />
namespace StudentApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class email_gender_made_required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(email_gender_made_required));
        
        string IMigrationMetadata.Id
        {
            get { return "202002280227032_email_gender_made_required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
